
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Installo i prerequisiti 
      apt: name=aptitude update_cache=yes state=latest 
      tags: [ system ]

    - name: Installo i pacchetti LAMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
      tags: [ system ]

    - name: Installo l'estensione PHP
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ php_modules }}"
      tags: [ system ]

  # Configurazione
    - name: Creo la dir di root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Installo il VirtualHost di Apache
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Ricarico apache
      tags: [ apache ]

    - name: Abilito il modulo rewrite
      shell: /usr/sbin/a2enmod rewrite
      notify: Ricarico apache
      tags: [ apache ]

    - name: Abilito il sito
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Ricarico apache
      tags: [ apache ]

    - name: Disabilito la conf di default di apache
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Ricarico apache
      tags: [ apache ]

  # Configurazione MySQL
    - name: Imposto la password di root
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: [ mysql, mysql-root ]


    - name: Creo il database per WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Creo l'utente  MySQL per WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

  # Configurazione UFW
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      tags: [ system ]

  # Configurazione Wordpress
    - name: Scarico e spacchetto l'ultima versione di WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
      tags: [ wordpress ]

    - name: Setto i permessi
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Setto i permessi alle direcotry
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Setto i permessi ai file
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]

    - name: Imposto il file di conf wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
      tags: [ wordpress ]

  handlers:
    - name: Ricarico apache
      service:
        name: apache2
        state: reloaded

    - name: Riavvio apache
      service:
        name: apache2
        state: restarted
